.PHONY: all clean
ALL = doodle_23-1 doodle_23-2 doodle_23-3 \
	listing_23-1 listing_23-2 listing_23-3 listing_23-5 listing_23-7 listing_23-8 \
	ex_23-1
CFLAGS = -Wall -Wextra -Wshadow -Werror -Wwrite-strings
LDFLAGS = -lrt

all: $(ALL)
clean::
	$(RM) $(ALL)
