.PHONY: all clean
ALL = doodle_27-1 doodle_27-3 doodle_27-4 doodle_27-5 \
	listing_27-1 listing_27-2 listing_27-3 listing_27-4 listing_27-5 listing_27-6 listing_27-7 \
	listing_27-8 listing_27-9 \
	ex_27-5 ex_27-6
CFLAGS = -Wall -Wextra -Wshadow -Werror

all: $(ALL)
clean::
	$(RM) $(ALL)
