.PHONY: all clean
ALL = listing_34-2 listing_34-3 listing_34-4 listing_34-5 listing_34-6 listing_34-7 \
	ex_34-2 ex_34-3 ex_34-4 ex_34-6
CFLAGS = -Wall -Wextra -Wshadow -Werror -Wwrite-strings

all: $(ALL)
clean::
	$(RM) $(ALL)
